version: 2
updates:
  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "05:00"
      timezone: Etc/UTC
