#!/usr/bin/env sh
# bump version, publish release, then bump back to dev
set -e

bumpversion --tag release
rm -rf dist
python setup.py sdist bdist_wheel
twine upload dist/*
bumpversion patch
git push
git push --tags
