name: release
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "**"

jobs:
  release-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: build release distributions
        run: |
          python -m pip install build
          python -m build .

      - name: upload dists
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository.name }}-dist
          path: dist/

  pypi-publish:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: release
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.repository.name }}-dist
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
